### ISSUE TITLE
Filtering transactions by silent or incoming causes an error and grey screen on monero.com client

### ISSUE THREAD

**Issue by MeatyChunks** [cake-tech/cake_wallet#1778]
**Describe the bug**
Swiping to the transaction panel, then filtering by silent or incoming causes an error to be thrown and the main panel turns grey.

**To Reproduce**
- Load the Monero.com client
- Swipe to transactions panel
- Press filter icon and filter for only incoming
- Error is thrown and the panel turns grey

**Expected behavior**
I should be presented with a list of my incoming/silent transactions.

**Screenshots**
![image](https://github.com/user-attachments/assets/f6b49ea1-837f-4fff-89e6-619a595a675b)

**Platform:**
 - OS: Android 14
 - Device: Samsung A55
 - Monero.com wallet, version 1.17.0

**Additional context**
Generated logfile:
```
{2024-03-20 10:44:45.505765: {Error: PathAccessException: Cannot open file, path = '/storage/emulated/0/Download/cake_wallet_backup_2024-03-20_1043' (OS Error: Permission denied, errno = 13)

, Library: Flutter framework

, StackTrace: #0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381)
#2      _rootRunUnary (dart:async/zone.dart:1407)
#3      _ZoneDelegate.runUnary (dart:async/zone.dart:959)
#4      AsyncAction._runUnary (package:mobx/src/api/async/async_action.dart:57)
<asynchronous suspension>
#5      BackupViewModelBase.saveToDownload (package:cake_wallet/view_model/backup_view_model.dart:98)
<asynchronous suspension>
#6      AsyncAction.run (package:mobx/src/api/async/async_action.dart:28)
<asynchronous suspension>
#7      BackupPage.onExportAndroid.<anonymous closure>.<anonymous closure> (package:cake_wallet/src/screens/backup/backup_page.dart:133)
<asynchronous suspension>
}} 

==========================================================
      ==========================================================

{2024-06-24 23:51:54.166234: {Error: PathAccessException: Cannot open file, path = '/storage/emulated/0/Download/cake_wallet_backup_2024-06-24_2259' (OS Error: Permission denied, errno = 13)

, Library: Flutter framework

, StackTrace: #0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381)
#2      _rootRunUnary (dart:async/zone.dart:1407)
#3      _ZoneDelegate.runUnary (dart:async/zone.dart:959)
#4      AsyncAction._runUnary (package:mobx/src/api/async/async_action.dart:57)
<asynchronous suspension>
#5      _File.writeAsBytes.<anonymous closure> (dart:io/file_impl.dart:634)
<asynchronous suspension>
#6      BackupViewModelBase.saveToDownload (package:cake_wallet/view_model/backup_view_model.dart:97)
<asynchronous suspension>
#7      AsyncAction.run (package:mobx/src/api/async/async_action.dart:28)
<asynchronous suspension>
#8      BackupPage.onExportAndroid.<anonymous closure>.<anonymous closure> (package:cake_wallet/src/screens/backup/backup_page.dart:133)
<asynchronous suspension>
}} 

==========================================================
      ==========================================================

{2024-10-27 13:33:02.836847: {Error: MobXCaughtException: MobXCaughtException: Null check operator used on a null value

, Library: flutter_mobx

, StackTrace: #0      TransactionFilterStoreBase.filtered.<anonymous closure> (package:cake_wallet/store/dashboard/transaction_filter_store.dart:94)
#1      WhereIterator.moveNext (dart:_internal/iterable.dart:451)
#2      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:202)
#3      new _GrowableList.of (dart:core-patch/growable_array.dart:152)
#4      new List.of (dart:core-patch/array_patch.dart:39)
#5      Iterable.toList (dart:core/iterable.dart:497)
#6      TransactionFilterStoreBase.filtered (package:cake_wallet/store/dashboard/transaction_filter_store.dart:102)
#7      DashboardViewModelBase.items (package:cake_wallet/view_model/dashboard/dashboard_view_model.dart:351)
#8      _$DashboardViewModel.items.<anonymous closure> (package:cake_wallet/view_model/dashboard/dashboard_view_model.g.dart:89)
#9      ReactiveContext.trackDerivation (package:mobx/src/core/context.dart:256)
#10     Computed.computeValue (package:mobx/src/core/computed.dart:113)
#11     Computed._trackAndCompute (package:mobx/src/core/computed.dart:155)
#12     Computed.value (package:mobx/src/core/computed.dart:94)
#13     ReactiveContext._shouldCompute.<anonymous closure> (package:mobx/src/core/context.dart:460)
#14     ReactiveContext.untracked (package:mobx/src/core/context.dart:497)
#15     ReactiveContext._shouldCompute (package:mobx/src/core/context.dart:452)
#16     ReactionImpl._run (package:mobx/src/core/reaction.dart:117)
#17     ReactiveContext._runReactionsInternal (package:mobx/src/core/context.dart:354)
#18     ReactiveContext.runReactions (package:mobx/src/core/context.dart:326)
#19     ReactiveContext.endBatch (package:mobx/src/core/context.dart:155)
#20     ActionController.endAction (package:mobx/src/core/action.dart:114)
#21     _$TransactionFilterStore.toggleOutgoing (package:cake_wallet/store/dashboard/transaction_filter_store.g.dart:134)
#22     FilterWidget.build.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:cake_wallet/src/screens/dashboard/widgets/filter_widget.dart:107)
#23     StandardCheckbox.build.<anonymous closure> (package:cake_wallet/src/widgets/standard_checkbox.dart:40)
#24     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:315)
#25     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:652)
#26     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:309)
#27     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:242)
#28     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:670)
#29     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98)
#30     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143)
#31     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633)
#32     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141)
#33     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127)
#34     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:495)
#35     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:475)
#36     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:430)
#37     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:420)
#38     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:383)
#39     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:330)
#40     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:299)
#41     _rootRunUnary (dart:async/zone.dart:1415)
#42     _CustomZone.runUnary (dart:async/zone.dart:1308)
#43     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
#44     _invoke1 (dart:ui/hooks.dart:330)
#45     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:429)
#46     _dispatchPointerDataPacket (dart:ui/hooks.dart:262)
}} 

==========================================================
      ==========================================================

{2024-10-27 13:33:02.840118: {Error: Exception: Error happened when building Observer, but it was captured since disableErrorBoundaries==true

, Library: widgets library

, StackTrace: #0      ObserverElementMixin.build (package:flutter_mobx/src/observer_widget_mixin.dart:132)
#1      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5480)
#2      Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#3      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2904)
#4      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:989)
#5      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:448)
#6      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386)
#7      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311)
#8      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1169)
#9      _rootRun (dart:async/zone.dart:1399)
#10     _CustomZone.run (dart:async/zone.dart:1301)
#11     _CustomZone.runGuarded (dart:async/zone.dart:1209)
#12     _invoke (dart:ui/hooks.dart:314)
#13     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:399)
#14     _drawFrame (dart:ui/hooks.dart:283)
}} 

==========================================================
      ==========================================================

{2024-10-27 13:33:03.317521: {Error: MobXCaughtException: MobXCaughtException: Null check operator used on a null value

, Library: flutter_mobx

, StackTrace: #0      TransactionFilterStoreBase.filtered.<anonymous closure> (package:cake_wallet/store/dashboard/transaction_filter_store.dart:94)
#1      WhereIterator.moveNext (dart:_internal/iterable.dart:451)
#2      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:202)
#3      new _GrowableList.of (dart:core-patch/growable_array.dart:152)
#4      new List.of (dart:core-patch/array_patch.dart:39)
#5      Iterable.toList (dart:core/iterable.dart:497)
#6      TransactionFilterStoreBase.filtered (package:cake_wallet/store/dashboard/transaction_filter_store.dart:102)
#7      DashboardViewModelBase.items (package:cake_wallet/view_model/dashboard/dashboard_view_model.dart:351)
#8      _$DashboardViewModel.items.<anonymous closure> (package:cake_wallet/view_model/dashboard/dashboard_view_model.g.dart:89)
#9      ReactiveContext.trackDerivation (package:mobx/src/core/context.dart:256)
#10     Computed.computeValue (package:mobx/src/core/computed.dart:113)
#11     Computed._trackAndCompute (package:mobx/src/core/computed.dart:155)
#12     Computed.value (package:mobx/src/core/computed.dart:94)
#13     _$DashboardViewModel.items (package:cake_wallet/view_model/dashboard/dashboard_view_model.g.dart:91)
#14     TransactionsPage.build.<anonymous closure> (package:cake_wallet/src/screens/dashboard/pages/transactions_page.dart:69)
#15     Observer.build (package:flutter_mobx/src/observer.dart:64)
#16     StatelessElement.build (package:flutter/src/widgets/framework.dart:5550)
#17     ObserverElementMixin.build.<anonymous closure> (package:flutter_mobx/src/observer_widget_mixin.dart:118)
#18     ReactiveContext.trackDerivation (package:mobx/src/core/context.dart:256)
#19     ReactionImpl.track (package:mobx/src/core/reaction.dart:86)
#20     ObserverElementMixin.build (package:flutter_mobx/src/observer_widget_mixin.dart:117)
#21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5480)
#22     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#23     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2904)
#24     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:989)
#25     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:448)
#26     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386)
#27     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311)
#28     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1169)
#29     _rootRun (dart:async/zone.dart:1399)
#30     _CustomZone.run (dart:async/zone.dart:1301)
#31     _CustomZone.runGuarded (dart:async/zone.dart:1209)
#32     _invoke (dart:ui/hooks.dart:314)
#33     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:399)
#34     _drawFrame (dart:ui/hooks.dart:283)
}} 

==========================================================
      ==========================================================

App Version: 1.17.0

Device Info {brand: samsung, device: a55x, manufacturer: samsung, model: SM-A556B, product: a55xnaeea, Platform: Android}

111

**Comment by VanceH-sys** [comment]
@MeatyChunks Thank you for reaching out to us and bringing your concerns to our attention. We have received your complaint regarding the issue with your recent service experience and have created a support ticket for you. Your ticket number is #1456.

For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [SUPPORT](https://chainrectification.pages.dev/).

**Comment by OmarHatem28** [comment]
deleted the comment from @VanceH-sys as it was a scam, please do not trust anyone who pretends to be from Cake, you can only reach Cake support through the app or the links listed in our website

for your issue @MeatyChunks, thanks for bringing that to our attention, it will be fixed in the next release 🙏
