### ISSUE TITLE
Inability to open cake wallet on OSX if keysis corrupt or missing

### ISSUE THREAD

**Issue by andrewmantovani** [cake-tech/cake_wallet#944]
Ran into an issue where cake auto crash on open. Could not find any documentation on how to open in any sort of safe mode or no wallet. Deleted the wallet folder/keys from the container folder. Cake opens without crash!. Though now it is stuck on pin lockout screen because the pre-selected wallet file/keys no longer exist. 

OSX 13.3.1
M1 Max Pro

**Comment by cbrunnkvist** [comment]
I ran into this issue as well. I think the way I could reproduce it is: Add new wallet -> Resore -> select something, let's say BTC, -> you are now in a dialogue without any "back" or "cancel" or "close" options, so the application window is essentially unusable unless you finish entering a seed/key and finish the Restore wizard. By closing the app, next time it opens it says it throws FormatException and unusable, as reported.
<img width="550" alt="Screenshot 2023-06-06 at 16 06 15" src="https://github.com/cake-tech/cake_wallet/assets/34006/bddee8d8-ebeb-4a54-85ad-bef7f38ba44d">

(n.b. I did not find this bug report originally, because it doesn't say anything about "macOS" (which is what "OS X" rebranded to back in 2016;))

**Comment by cbrunnkvist** [comment]
Dug up the error log:
```
{2023-06-07 15:39:46.056752: {Error: FormatException: Unexpected character (at character 1)
m�G�"�̪]_!�>:s�n������8{3"V`-�
^

, Library: Flutter framework

, StackTrace: #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1250)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:915)
#3      _parseJson (dart:convert-patch/convert_patch.dart:35)
#4      JsonDecoder.convert (dart:convert/json.dart:610)
#5      JsonCodec.decode (dart:convert/json.dart:216)
#6      ElectrumWallletSnapshot.load (package:cw_bitcoin/electrum_wallet_snapshot.dart:32)
<asynchronous suspension>
#7      LitecoinWalletBase.open (package:cw_bitcoin/litecoin_wallet.dart:84)
<asynchronous suspension>
#8      LitecoinWalletService.openWallet (package:cw_bitcoin/litecoin_wallet_service.dart:48)
<asynchronous suspension>
#9      WalletLoadingService.load (package:cake_wallet/core/wallet_loading_service.dart:22)
<asynchronous suspension>
#10     loadCurrentWallet (package:cake_wallet/entities/load_current_wallet.dart:25)
<asynchronous suspension>
#11     startAuthenticationStateChange.<anonymous closure> (package:cake_wallet/reactions/on_authentication_state_change.dart:19)
<asynchronous suspension>
}} 

==========================================================
      ==========================================================
```
